version: "3.7"
services:

  app:
    build: './app'
    ports:
      - "5000:5000"
    depends_on:
      - postgres_container
      - rabbit
      - mongodb_container

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"

  mongodb_container:
    image: mongo:latest
    ports:
      - "27017:27017"
  postgres_container:
     build: ./database/
  redis:
    image: "redis:alpine"
  broker:
    build: './broker'
    user: nobody
    depends_on:
      - postgres_container
      - rabbit
      - app
      - mongodb_container
